#!/bin/bash

if [ -z "$1" ]; then
  echo "Usage: $0 <source_directory>"
  exit 1
fi

# 修正：变量赋值时不能有空格
SOURCE_DIR="$1"
DELOMBOK_DIR="delombok"

# 检查源目录是否存在
if [ ! -d "$SOURCE_DIR" ]; then
  echo "Error: Source directory '$SOURCE_DIR' does not exist."
  exit 1
fi

# 检查 lombok.jar 是否存在
if [ ! -f "lombok.jar" ]; then
  echo "Error: lombok.jar not found in current directory."
  exit 1
fi

# 运行 "delombok" 命令
java -jar "lombok.jar" delombok -n --onlyChanged "$SOURCE_DIR" -d "$DELOMBOK_DIR"

# 检查 delombok 是否成功执行
if [ $? -ne 0 ]; then
  echo "Error: Delombok command failed."
  exit 1
fi

# 删除生成的注释评论
find "$DELOMBOK_DIR" -name '*.java' -exec sed -i '/Generated by delombok/d' {} \;

# 删除 Lombok 导入语句
find "$DELOMBOK_DIR" -name '*.java' -exec sed -i '/import lombok/d' {} \;

# 删除多余的注释
find "$DELOMBOK_DIR" -name '*.java' -exec sed -i '/@java.lang.SuppressWarnings("all")/d' {} \;
find "$DELOMBOK_DIR" -name '*.java' -exec sed -i '/@lombok.Generated/d' {} \;

# 将转换后的文件复制回原目录
cp -r "$DELOMBOK_DIR/." "$SOURCE_DIR"

# 删除 "delombok" 目录
rm -rf "$DELOMBOK_DIR"

echo "Delombok process completed successfully."