@echo off
setlocal enabledelayedexpansion

REM 检查参数
if "%1"=="" (
    echo Usage: %0 ^<source_directory^>
    exit /b 1
)

set SOURCE_DIR=%1
set DELOMBOK_DIR=delombok

REM 检查源目录是否存在
if not exist "%SOURCE_DIR%" (
    echo Error: Source directory '%SOURCE_DIR%' does not exist.
    exit /b 1
)

REM 检查 lombok.jar 是否存在
if not exist "lombok.jar" (
    echo Error: lombok.jar not found in current directory.
    exit /b 1
)

REM 运行 delombok 命令
echo Running delombok on %SOURCE_DIR%...
java -jar "lombok.jar" delombok -n --onlyChanged "%SOURCE_DIR%" -d "%DELOMBOK_DIR%"

REM 检查 delombok 是否成功执行
if %errorlevel% neq 0 (
    echo Error: Delombok command failed.
    exit /b 1
)

REM 检查 delombok 目录是否创建成功
if not exist "%DELOMBOK_DIR%" (
    echo Error: Delombok directory was not created.
    exit /b 1
)

echo Cleaning up generated files...

REM 删除生成的注释评论和Lombok相关代码
for /R "%DELOMBOK_DIR%" %%f in (*.java) do (
    if exist "%%f" (
        REM 创建临时文件
        findstr /v /c:"// Generated by delombok" "%%f" | findstr /v /c:"import lombok" | findstr /v /c:"@java.lang.SuppressWarnings("all")" | findstr /v /c:"@lombok.Generated" > "%%f.tmp"
        move /y "%%f.tmp" "%%f" >nul
    )
)

REM 将转换后的文件复制回原目录
echo Copying files back to source directory...
xcopy "%DELOMBOK_DIR%\*" "%SOURCE_DIR%\" /s /e /y

REM 删除 delombok 目录
rmdir /s /q "%DELOMBOK_DIR%"

echo Delombok process completed successfully.